#!/usr/bin/env bash
if [ ! -f ~/.config/login-sound.conf ]; then
  cp /etc/login-sound.conf ~/.config/login-sound.conf
fi
source ~/.config/login-sound.conf
ogg123 /usr/share/sounds/login/$LOGIN_SOUND.ogg > /dev/null 2>&1 &
